spring.application.name=pracJournalApp
spring.data.mongodb.uri=mongodb+srv://harsh:harsh%402005@cluster0.ayfubhj.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=pracJournaldb
spring.data.mongodb.auto-index-creation=true