spring.application.name=pracJournalApp


#redis connection
spring.data.redis.url=redis://default:5XSrUFm6Iq5qZf1JbWU6exMY81GMcZqT@redis-10970.crce281.ap-south-1-3.ec2.cloud.redislabs.com:10970


#kafka connection
spring.kafka.bootstrap-servers=my-kafka-cluster-gharshgupta490-3478.d.aivencloud.com:24567

spring.kafka.consumer.group-id=weekly-sentiment-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN

spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="avnadmin" password="${KAFKA_PASSWORD}";

spring.kafka.properties.session.timeout.ms=45000

# Kafka SSL configuration (Bypassing PKIX with custom factory)
spring.kafka.properties.ssl.engine.factory.class=com.example.pracJournalApp.config.TrustAllSslEngineFactory

spring.kafka.properties.ssl.protocol=TLSv1.2
spring.kafka.properties.ssl.endpoint.identification.algorithm=
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.pracJournalApp.model

#database connection
spring.data.mongodb.uri=mongodb+srv://harsh:harsh%402005@cluster0.ayfubhj.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=pracJournaldb
spring.data.mongodb.auto-index-creation=true
weather.app.api=0273a28144cf4d039b4211100665bd96

#mail connection
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gharshgupta490@gmail.com
spring.mail.password=miow mwcg dxxu qixh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true